package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockDao;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int insert(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int insertSelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    ItemStockDao selectByPrimaryKey(Integer id);


    //通过itemId获取ItemStock表中库存
    ItemStockDao selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDao record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int updateByPrimaryKey(ItemStockDao record);
}