package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */

    List<ItemDao> listItem();

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int insert(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int insertSelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    ItemDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 13 10:32:08 CST 2019
     */
    int updateByPrimaryKey(ItemDao record);

    void increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}